licenses:
  - ISC
  - MIT
  - BSD-2-Clause
  - CC-BY-3.0
  - CC0-1.0
  - BSD-3-Clause
modules:
  - abbrev@1.1.1
  - ansi-escapes@3.1.0
  - ansi-regex@3.0.0
  - color-name@1.1.3
  - commander@2.19.0
  - concat-map@0.0.1
  - debug@3.2.6
  - debuglog@1.0.1
  - dezalgo@1.0.3
  - escape-string-regexp@1.0.5
  - esprima@4.0.1
  - external-editor@3.0.3
  - figures@2.0.0
  - fs-extra@7.0.1
  - license-checker@24.1.0
  - sprintf-js@1.0.3
  - rxjs@6.3.3
  - spdx-correct@3.1.0
  - tslib@1.9.3
